apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: sviry/query
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    # should match with template=>metadata=>labels=>app
    app: query
  # may not specify due to default value will be ClusterIP
  type: ClusterIP
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002